# Generated by tools/generate_sync.py. Do not edit.
from __future__ import annotations

from typing import Any

from sci_etl_core.pipeline_async import AsyncETLPipeline
from sci_etl_core._sync_bridge import run_sync


class ETLPipeline(object):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        object.__setattr__(self, '_impl', AsyncETLPipeline(*args, **kwargs))
    def run(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.run(*args, **kwargs))
    @staticmethod
    def _resolve_limits(*args: Any, **kwargs: Any) -> Any:
        return AsyncETLPipeline._resolve_limits(*args, **kwargs)
    def _process_record(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl._process_record(*args, **kwargs))
    def _mark_done(self, *args: Any, **kwargs: Any) -> Any:
        return self._impl._mark_done(*args, **kwargs)
    def __getattr__(self, name: str) -> Any:
        if name == '_impl':
            raise AttributeError(name)
        return getattr(self._impl, name)
    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._impl, name, value)
