# Generated by tools/generate_sync.py. Do not edit.
from __future__ import annotations

from typing import Any

from sci_etl_core.extractors.arxiv_async import AsyncArxivExtractor
from sci_etl_core.extractors.base import Extractor
from sci_etl_core._sync_bridge import run_sync


class ArxivExtractor(Extractor):
    API_URL = AsyncArxivExtractor.API_URL
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        object.__setattr__(self, '_impl', AsyncArxivExtractor(*args, **kwargs))
    def search(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.search(*args, **kwargs))
    def parse_listing(self, *args: Any, **kwargs: Any) -> Any:
        return self._impl.parse_listing(*args, **kwargs)
    def _normalize_id(self, *args: Any, **kwargs: Any) -> Any:
        return self._impl._normalize_id(*args, **kwargs)
    def _strip_version(self, *args: Any, **kwargs: Any) -> Any:
        return self._impl._strip_version(*args, **kwargs)
    def fetch_full_text(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.fetch_full_text(*args, **kwargs))
    def _fetch_latex_source(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl._fetch_latex_source(*args, **kwargs))
    def _fetch_pdf_text(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl._fetch_pdf_text(*args, **kwargs))
    def _get_bytes(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl._get_bytes(*args, **kwargs))
    def __getattr__(self, name: str) -> Any:
        if name == '_impl':
            raise AttributeError(name)
        return getattr(self._impl, name)
    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._impl, name, value)
