# Generated by tools/generate_sync.py. Do not edit.
from __future__ import annotations

from typing import Any

from sci_etl_core.state.async_file_state import AsyncFileStateManager
from sci_etl_core.state.base import StateManager
from sci_etl_core._sync_bridge import run_sync


class FileStateManager(StateManager):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        object.__setattr__(self, '_impl', AsyncFileStateManager(*args, **kwargs))
    def load_processed_ids(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.load_processed_ids(*args, **kwargs))
    def mark_processed(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.mark_processed(*args, **kwargs))
    def load_metadata(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.load_metadata(*args, **kwargs))
    def save_metadata(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.save_metadata(*args, **kwargs))
    def __getattr__(self, name: str) -> Any:
        if name == '_impl':
            raise AttributeError(name)
        return getattr(self._impl, name)
    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._impl, name, value)
