# Generated by tools/generate_sync.py. Do not edit.
from __future__ import annotations

from typing import Any

from sci_etl_core.exporters.plotly_async import AsyncPlotly3DExporter
from sci_etl_core.exporters.plotly_async import ScatterPlotConfig
from sci_etl_core.exporters.base import Exporter
from sci_etl_core._sync_bridge import run_sync


class Plotly3DExporter(Exporter):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        object.__setattr__(self, '_impl', AsyncPlotly3DExporter(*args, **kwargs))
    def export(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.export(*args, **kwargs))
    def _render(self, *args: Any, **kwargs: Any) -> Any:
        return self._impl._render(*args, **kwargs)
    def __getattr__(self, name: str) -> Any:
        if name == '_impl':
            raise AttributeError(name)
        return getattr(self._impl, name)
    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._impl, name, value)
