# Generated by tools/generate_sync.py. Do not edit.
from __future__ import annotations

from typing import Any

from sci_etl_core.llm.extraction_async import AsyncLLMEntityExtractor
from sci_etl_core._sync_bridge import run_sync
from abc import ABC, abstractmethod


class EntityExtractor(ABC):

    @abstractmethod
    def extract(self, text: str | bytes) -> list[dict[str, Any]]:
        """Extract structured entities from raw text."""


class LLMEntityExtractor(EntityExtractor):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        object.__setattr__(self, '_impl', AsyncLLMEntityExtractor(*args, **kwargs))
    def extract(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.extract(*args, **kwargs))
    def _truncate(self, *args: Any, **kwargs: Any) -> Any:
        return self._impl._truncate(*args, **kwargs)
    def __getattr__(self, name: str) -> Any:
        if name == '_impl':
            raise AttributeError(name)
        return getattr(self._impl, name)
    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._impl, name, value)
