# Generated by tools/generate_sync.py. Do not edit.
from __future__ import annotations

from typing import Any

from sci_etl_core.llm.openai_compatible_async import AsyncOpenAICompatibleClient
from sci_etl_core.llm.base import LLMClient
from sci_etl_core._sync_bridge import run_sync


class OpenAICompatibleClient(LLMClient):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        object.__setattr__(self, '_impl', AsyncOpenAICompatibleClient(*args, **kwargs))
    def complete_json(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.complete_json(*args, **kwargs))
    @staticmethod
    def _parse(*args: Any, **kwargs: Any) -> Any:
        return AsyncOpenAICompatibleClient._parse(*args, **kwargs)
    def __getattr__(self, name: str) -> Any:
        if name == '_impl':
            raise AttributeError(name)
        return getattr(self._impl, name)
    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._impl, name, value)
