# Generated by tools/generate_sync.py. Do not edit.
from __future__ import annotations

from typing import Any

from sci_etl_core.llm.relevance_async import AsyncLLMRelevanceFilter
from sci_etl_core._sync_bridge import run_sync
from abc import ABC, abstractmethod


class RelevanceFilter(ABC):

    @abstractmethod
    def is_relevant(self, record: RawRecord) -> bool:
        """Decide whether a record should proceed through the pipeline."""


class LLMRelevanceFilter(RelevanceFilter):
    def __init__(self, *args: Any, **kwargs: Any) -> None:
        object.__setattr__(self, '_impl', AsyncLLMRelevanceFilter(*args, **kwargs))
    def is_relevant(self, *args: Any, **kwargs: Any) -> Any:
        return run_sync(self._impl.is_relevant(*args, **kwargs))
    def __getattr__(self, name: str) -> Any:
        if name == '_impl':
            raise AttributeError(name)
        return getattr(self._impl, name)
    def __setattr__(self, name: str, value: Any) -> None:
        setattr(self._impl, name, value)
