from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass, field
from pathlib import Path


@dataclass(frozen=True)
class AbcSpec:
    async_name: str
    sync_name: str


@dataclass(frozen=True)
class FacadeSpec:
    async_name: str
    sync_name: str
    sync_base: str | None = None


@dataclass(frozen=True)
class ModuleSpec:
    async_module: str
    sync_module: str
    abcs: tuple[AbcSpec, ...] = ()
    facades: tuple[FacadeSpec, ...] = ()
    reexports: tuple[tuple[str, str], ...] = ()
    base_imports: tuple[str, ...] = ()


REGISTRY: tuple[ModuleSpec, ...] = (
    ModuleSpec(
        async_module="sci_etl_core.extractors.arxiv_async",
        sync_module="sci_etl_core.extractors.arxiv",
        facades=(FacadeSpec("AsyncArxivExtractor", "ArxivExtractor", "Extractor"),),
        base_imports=("from sci_etl_core.extractors.base import Extractor",),
    ),
    ModuleSpec(
        async_module="sci_etl_core.llm.openai_compatible_async",
        sync_module="sci_etl_core.llm.openai_compatible",
        facades=(FacadeSpec("AsyncOpenAICompatibleClient", "OpenAICompatibleClient", "LLMClient"),),
        base_imports=("from sci_etl_core.llm.base import LLMClient",),
    ),
    ModuleSpec(
        async_module="sci_etl_core.llm.extraction_async",
        sync_module="sci_etl_core.llm.extraction",
        abcs=(AbcSpec("AsyncEntityExtractor", "EntityExtractor"),),
        facades=(FacadeSpec("AsyncLLMEntityExtractor", "LLMEntityExtractor", "EntityExtractor"),),
    ),
    ModuleSpec(
        async_module="sci_etl_core.llm.relevance_async",
        sync_module="sci_etl_core.llm.relevance",
        abcs=(AbcSpec("AsyncRelevanceFilter", "RelevanceFilter"),),
        facades=(FacadeSpec("AsyncLLMRelevanceFilter", "LLMRelevanceFilter", "RelevanceFilter"),),
    ),
    ModuleSpec(
        async_module="sci_etl_core.pipeline_async",
        sync_module="sci_etl_core.pipeline",
        facades=(FacadeSpec("AsyncETLPipeline", "ETLPipeline", None),),
    ),
    ModuleSpec(
        async_module="sci_etl_core.exporters.csv_async",
        sync_module="sci_etl_core.exporters.csv_exporter",
        facades=(FacadeSpec("AsyncCsvUpsertExporter", "CsvUpsertExporter", "Exporter"),),
        base_imports=("from sci_etl_core.exporters.base import Exporter",),
    ),
    ModuleSpec(
        async_module="sci_etl_core.exporters.plotly_async",
        sync_module="sci_etl_core.exporters.plotly_exporter",
        facades=(FacadeSpec("AsyncPlotly3DExporter", "Plotly3DExporter", "Exporter"),),
        reexports=(("sci_etl_core.exporters.plotly_async", "ScatterPlotConfig"),),
        base_imports=("from sci_etl_core.exporters.base import Exporter",),
    ),
    ModuleSpec(
        async_module="sci_etl_core.exporters.sql_async",
        sync_module="sci_etl_core.exporters.sql_exporter",
        facades=(FacadeSpec("AsyncSqlTableExporter", "SqlTableExporter", "Exporter"),),
        base_imports=("from sci_etl_core.exporters.base import Exporter",),
    ),
    ModuleSpec(
        async_module="sci_etl_core.state.async_file_state",
        sync_module="sci_etl_core.state.file_state",
        facades=(FacadeSpec("AsyncFileStateManager", "FileStateManager", "StateManager"),),
        base_imports=("from sci_etl_core.state.base import StateManager",),
    ),
)

_HEADER = "# Generated by tools/generate_sync.py. Do not edit."


class _Renamer(ast.NodeTransformer):
    def __init__(self, mapping: dict[str, str]) -> None:
        self._mapping = mapping

    def visit_Name(self, node: ast.Name) -> ast.AST:
        if node.id in self._mapping:
            return ast.copy_location(ast.Name(id=self._mapping[node.id], ctx=node.ctx), node)
        return node


def _module_to_path(src_root: Path, module: str) -> Path:
    return src_root.joinpath(*module.split(".")).with_suffix(".py")


def _classes(tree: ast.Module) -> dict[str, ast.ClassDef]:
    return {node.name: node for node in tree.body if isinstance(node, ast.ClassDef)}


def _desugar_abc(node: ast.ClassDef, mapping: dict[str, str]) -> str:
    clone = ast.parse(ast.unparse(node)).body[0]
    clone.name = mapping.get(node.name, node.name)
    new_body: list[ast.stmt] = []
    for stmt in clone.body:
        if isinstance(stmt, ast.AsyncFunctionDef):
            stmt = ast.FunctionDef(
                name=stmt.name,
                args=stmt.args,
                body=stmt.body,
                decorator_list=stmt.decorator_list,
                returns=stmt.returns,
                type_comment=stmt.type_comment,
            )
        new_body.append(stmt)
    clone.body = new_body
    clone = _Renamer(mapping).visit(clone)
    ast.fix_missing_locations(clone)
    return ast.unparse(clone)


def _is_static(func: ast.AST) -> bool:
    return any(
        isinstance(dec, ast.Name) and dec.id == "staticmethod" for dec in func.decorator_list
    )


def _is_dunder(name: str) -> bool:
    return name.startswith("__") and name.endswith("__")


def _facade(node: ast.ClassDef, spec: FacadeSpec) -> str:
    base = spec.sync_base or "object"
    lines: list[str] = [f"class {spec.sync_name}({base}):"]

    for stmt in node.body:
        if isinstance(stmt, ast.Assign):
            for target in stmt.targets:
                if isinstance(target, ast.Name):
                    lines.append(f"    {target.id} = {spec.async_name}.{target.id}")

    lines.append("    def __init__(self, *args: Any, **kwargs: Any) -> None:")
    lines.append(f"        object.__setattr__(self, '_impl', {spec.async_name}(*args, **kwargs))")

    for stmt in node.body:
        is_async = isinstance(stmt, ast.AsyncFunctionDef)
        is_sync = isinstance(stmt, ast.FunctionDef)
        if not (is_async or is_sync):
            continue
        name = stmt.name
        if _is_dunder(name):
            continue
        static = _is_static(stmt)
        if static and is_async:
            lines.append("    @staticmethod")
            lines.append(f"    def {name}(*args: Any, **kwargs: Any) -> Any:")
            lines.append(f"        return run_sync({spec.async_name}.{name}(*args, **kwargs))")
        elif static:
            lines.append("    @staticmethod")
            lines.append(f"    def {name}(*args: Any, **kwargs: Any) -> Any:")
            lines.append(f"        return {spec.async_name}.{name}(*args, **kwargs)")
        elif is_async:
            lines.append(f"    def {name}(self, *args: Any, **kwargs: Any) -> Any:")
            lines.append(f"        return run_sync(self._impl.{name}(*args, **kwargs))")
        else:
            lines.append(f"    def {name}(self, *args: Any, **kwargs: Any) -> Any:")
            lines.append(f"        return self._impl.{name}(*args, **kwargs)")

    lines.append("    def __getattr__(self, name: str) -> Any:")
    lines.append("        if name == '_impl':")
    lines.append("            raise AttributeError(name)")
    lines.append("        return getattr(self._impl, name)")
    lines.append("    def __setattr__(self, name: str, value: Any) -> None:")
    lines.append("        setattr(self._impl, name, value)")
    return "\n".join(lines)


def render(spec: ModuleSpec, src_root: Path) -> str:
    tree = ast.parse(_module_to_path(src_root, spec.async_module).read_text(encoding="utf-8"))
    classes = _classes(tree)

    imports: list[str] = ["from __future__ import annotations", "", "from typing import Any", ""]
    needed = [s.async_name for s in spec.facades]
    if needed:
        imports.append(f"from {spec.async_module} import {', '.join(sorted(set(needed)))}")
    for module, name in spec.reexports:
        imports.append(f"from {module} import {name}")
    imports.extend(spec.base_imports)
    if spec.facades:
        imports.append("from sci_etl_core._sync_bridge import run_sync")

    mapping = {a.async_name: a.sync_name for a in spec.abcs}
    blocks: list[str] = []
    for abc in spec.abcs:
        blocks.append(_desugar_abc(classes[abc.async_name], mapping))
    for facade in spec.facades:
        blocks.append(_facade(classes[facade.async_name], facade))

    abc_prelude = ""
    if spec.abcs:
        abc_prelude = "from abc import ABC, abstractmethod\n"

    body = "\n\n\n".join(blocks)
    return f"{_HEADER}\n" + "\n".join(imports) + "\n" + abc_prelude + "\n\n" + body + "\n"


def generate(src_root: Path) -> list[Path]:
    written: list[Path] = []
    for spec in REGISTRY:
        target = _module_to_path(src_root, spec.sync_module)
        target.write_text(render(spec, src_root), encoding="utf-8")
        written.append(target)
    return written


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--src", default="src")
    args = parser.parse_args()
    for path in generate(Path(args.src).resolve()):
        print(path)


if __name__ == "__main__":
    main()
